version: '2.4'
services:

  backend:
    build:
      context: ./backend
      args:
        build_version: 1
        app_env: ${APP_ENV}
    image: backend
    environment:
      - NODE_ENV=development
      # - OMDb_PERSONAL_ACCESS_TOKEN=
    volumes:
      - ./backend:/app
    ports:
      - "3003:3003"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3003 && echo 'cool, it works'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    # depends_on: [ db ]

  frontend:
    build:
      context: ./frontend
      args:
        build_version: 1
        app_env: ${APP_ENV}
    image: frontend
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend/app:/app/app
    ports:
      - "3000:3000"
    depends_on: [ backend ]

  # db:
  #   build: ./db
  #   image: postgres
  #   volumes:
  #     - ./db/pgdata:/pgdata
  #   ports:
  #     - "5433:5432"
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - PGDATA=/pgdata
  #   command: psql -U postgres -p 5432 -h postgres
